// src/routes/login/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';

	let { form }: { form: { error?: string; email?: string } | null } = $props();
	let loading = $state(false);
</script>

<svelte:head>
	<title>Garmin Connect Login</title>
</svelte:head>

<main class="login-container">
	<div class="login-card">
		<div class="header">
			<svg
				class="garmin-logo"
				viewBox="0 0 100 100"
				fill="none"
				stroke="currentColor"
				stroke-width="2.5"
			>
				<circle cx="50" cy="50" r="42" stroke="currentColor" stroke-width="3" />
				<path d="M50 20 L32 68 L68 68 Z" fill="currentColor" />
				<circle cx="50" cy="48" r="6" fill="white" />
			</svg>
			<h1>Garmin Connect</h1>
			<p class="muted text-center">
				Enter your Garmin Connect credentials to sync your training and activity data.
			</p>
		</div>

		{#if form?.error}
			<p class="error text-center">{form.error}</p>
		{/if}

		<form
			method="POST"
			use:enhance={() => {
				loading = true;
				return async ({ update }) => {
					loading = false;
					await update();
				};
			}}
			class="login-form"
		>
			<label class="form-field">
				<span>Email Address</span>
				<input
					type="email"
					name="email"
					value={form?.email ?? ''}
					placeholder="your.email@example.com"
					required
					disabled={loading}
				/>
			</label>

			<label class="form-field">
				<span>Password</span>
				<input type="password" name="password" placeholder="••••••••" required disabled={loading} />
			</label>

			<button type="submit" class="submit-btn" disabled={loading}>
				{#if loading}
					Connecting to Garmin...
				{:else}
					Connect Account
				{/if}
			</button>
		</form>
	</div>
</main>

<style>
	.login-container {
		display: flex;
		justify-content: center;
		align-items: center;
		min-height: 80vh;
		max-width: 440px;
		margin: 0 auto;
		padding: 2rem 1rem;
	}

	.login-card {
		width: 100%;
		background: white;
		border: 1px solid #e5e7eb;
		border-radius: 16px;
		padding: 2rem;
		box-shadow:
			0 4px 6px -1px rgba(0, 0, 0, 0.05),
			0 2px 4px -1px rgba(0, 0, 0, 0.02);
	}

	.header {
		display: flex;
		flex-direction: column;
		align-items: center;
		margin-bottom: 2rem;
		text-align: center;
	}

	.garmin-logo {
		width: 56px;
		height: 56px;
		color: #111827;
		margin-bottom: 1rem;
	}

	.login-form {
		display: flex;
		flex-direction: column;
		gap: 1.25rem;
	}

	.form-field {
		display: flex;
		flex-direction: column;
		gap: 0.35rem;
		font-size: 0.9rem;
		color: #374151;
	}

	.form-field input {
		border-radius: 10px;
		border: 1px solid #d1d5db;
		padding: 0.65rem 0.85rem;
		font: inherit;
		width: 100%;
		box-sizing: border-box;
	}

	.form-field input:focus {
		outline: none;
		border-color: #111827;
		box-shadow: 0 0 0 1px #111827;
	}

	.submit-btn {
		width: 100%;
		padding: 0.75rem;
		border-radius: 10px;
		border: none;
		background: #111827;
		color: white;
		font-weight: 500;
		cursor: pointer;
		margin-top: 0.5rem;
		transition: background 0.15s ease;
	}

	.submit-btn:hover:not(:disabled) {
		background: #1f2937;
	}

	.submit-btn:disabled {
		opacity: 0.6;
		cursor: not-allowed;
	}

	.text-center {
		text-align: center;
	}

	.error {
		color: #b91c1c;
		background-color: #fef2f2;
		border: 1px solid #fca5a5;
		border-radius: 10px;
		padding: 0.75rem;
		margin-bottom: 1.5rem;
		font-size: 0.875rem;
	}
</style>

// app/login/page.tsx
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Sign In — purecadence.ai",
  description: "Sign in to your purecadence.ai account to access your Garmin training assistant.",
};

export default function LoginPage() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-slate-50 px-4">
      <div className="w-full max-w-sm">
        {/* Logo */}
        <div className="mb-8 text-center">
          <Link href="/" className="inline-flex items-center gap-2">
            <svg
              className="h-8 w-8 text-indigo-600"
              viewBox="0 0 100 100"
              fill="none"
              stroke="currentColor"
              strokeWidth={3}
            >
              <circle cx="50" cy="50" r="42" stroke="currentColor" strokeWidth={4} />
              <path d="M50 20 L32 68 L68 68 Z" fill="currentColor" />
              <circle cx="50" cy="48" r="6" fill="white" />
            </svg>
            <span className="text-xl font-bold tracking-tight text-slate-950">
              purecadence.ai
            </span>
          </Link>
        </div>

        {/* Card */}
        <div className="rounded-2xl border border-slate-200 bg-white p-8 shadow-sm">
          <h1 className="text-xl font-bold text-slate-950">Sign in</h1>
          <p className="mt-1 text-sm text-slate-500">
            Enter your Garmin Connect credentials to get started.
          </p>

          <form className="mt-6 space-y-4">
            <div>
              <label
                htmlFor="email"
                className="block text-sm font-medium text-slate-700"
              >
                Email
              </label>
              <input
                id="email"
                name="email"
                type="email"
                autoComplete="email"
                required
                className="mt-1 block w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-900 placeholder:text-slate-400 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500"
                placeholder="you@example.com"
              />
            </div>

            <div>
              <label
                htmlFor="password"
                className="block text-sm font-medium text-slate-700"
              >
                Password
              </label>
              <input
                id="password"
                name="password"
                type="password"
                autoComplete="current-password"
                required
                className="mt-1 block w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-900 placeholder:text-slate-400 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500"
                placeholder="••••••••"
              />
            </div>

            <button
              type="submit"
              className="w-full rounded-full bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-700 transition"
            >
              Sign In
            </button>
          </form>
        </div>

        <p className="mt-6 text-center text-xs text-slate-400">
          Your credentials are encrypted and used solely to establish a secure
          session with Garmin Connect.
        </p>
      </div>
    </div>
  );
}
